apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayfolder
  labels:
    app: ayfolder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ayfolder
  template:
    metadata:
      labels:
        app: ayfolder
    spec:
      containers:
        - name: ayfolder
          image: ${{ secrets.DOCKER_USERNAME }}/ayfolder:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10